name: Build Technology Radar

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REACT_APP_RADAR_NAME: "App Radar Name"
  APP_TITLE: "App Title"
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Set env variables
        run: |
          echo "REACT_APP_RADAR_NAME=${REACT_APP_RADAR_NAME}" >> $GITHUB_ENV
          echo "APP_TITLE=App Title 2" >> $GITHUB_ENV
      - name: Test env variables
        run: | 
            echo ${{ env.REACT_APP_RADAR_NAME }}
            echo ${{ env.APP_TITLE }}
      - run: npm ci
      - run: PUBLIC_URL=/tech-radar-example-pagopa npm run build:static
      - run: if [ -n "$(git status --porcelain)" ]; then echo 'workspace is dirty after rebuilding' ; git status ; git diff ; exit 1 ; fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: build

  deploy:
    # runs only when pr is merged into main or when a push is done on main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    needs: build
    environment:
      name: techradar
      url: https://billbosiolis.github.io/tech-radar-example-pagopa/index.html

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
